import type { CallEvaluation } from "./types";

const base = {
  recording_url: null,
  ai_model: "llama-3.3-70b-versatile",
  raw_payload: { source: "demo", workflow_version: "1.0" },
};

export const demoEvaluations: CallEvaluation[] = [
  {
    ...base, id: "demo-001", external_call_id: "ghl_demo_001", agent_id: "agent-maya", agent_name: "Maya Santos",
    contact_name: "Olivia Martin", contact_phone: "+1 (555) 014-2291", direction: "outbound", started_at: "2026-07-25T06:24:00.000Z",
    duration_seconds: 842, overall_score: 92, outcome: "won", sentiment: "positive",
    summary: "Maya uncovered the buyer's timeline, confirmed budget, and secured a strategy call with both decision-makers.",
    strengths: ["Clear agenda setting", "Strong follow-up questions", "Specific next step"],
    improvements: ["Leave a little more room after asking about budget"],
    rubric_scores: { opening: 95, discovery: 94, communication: 91, objection_handling: 88, closing: 94 },
    transcript: "Agent: Hi Olivia, this is Maya from Northstar. Is now still a good time?\n\nContact: Yes, I have about fifteen minutes.\n\nAgent: Perfect. I’d like to understand what you’re trying to improve, then we can see if a strategy session makes sense. What prompted you to look at this now?\n\nContact: Our lead volume is growing, but our follow-up is inconsistent...",
    created_at: "2026-07-25T06:40:00.000Z",
  },
  {
    ...base, id: "demo-002", external_call_id: "ghl_demo_002", agent_id: "agent-liam", agent_name: "Liam Chen",
    contact_name: "Noah Williams", contact_phone: "+1 (555) 016-8842", direction: "inbound", started_at: "2026-07-25T04:10:00.000Z",
    duration_seconds: 611, overall_score: 87, outcome: "follow_up", sentiment: "positive",
    summary: "Liam handled pricing concerns calmly and earned permission to follow up after the prospect's internal review.",
    strengths: ["Concise value explanation", "Good tone control", "Confirmed follow-up date"],
    improvements: ["Ask who else is involved in approval"],
    rubric_scores: { opening: 88, discovery: 82, communication: 93, objection_handling: 91, closing: 84 },
    transcript: "Agent: Thanks for calling Northstar, this is Liam. How can I help?\n\nContact: I saw your pricing page and wanted to understand what is included.\n\nAgent: Absolutely. Before I walk through that, could I ask what your team is hoping to solve?",
    created_at: "2026-07-25T04:24:00.000Z",
  },
  {
    ...base, id: "demo-003", external_call_id: "ghl_demo_003", agent_id: "agent-sofia", agent_name: "Sofia Reyes",
    contact_name: "Emma Thompson", contact_phone: "+1 (555) 017-1264", direction: "outbound", started_at: "2026-07-24T22:38:00.000Z",
    duration_seconds: 476, overall_score: 78, outcome: "follow_up", sentiment: "neutral",
    summary: "Sofia established interest but moved to the product explanation before fully exploring the prospect's current process.",
    strengths: ["Warm opening", "Accurate product explanation"],
    improvements: ["Explore the current workflow first", "Use open-ended discovery questions"],
    rubric_scores: { opening: 89, discovery: 64, communication: 85, objection_handling: 76, closing: 78 },
    transcript: "Agent: Hi Emma, Sofia here from Northstar. How is your afternoon going?\n\nContact: Good, thanks. I only have a few minutes.\n\nAgent: No problem. We help teams automate lead follow-up across channels...",
    created_at: "2026-07-24T22:50:00.000Z",
  },
  {
    ...base, id: "demo-004", external_call_id: "ghl_demo_004", agent_id: "agent-maya", agent_name: "Maya Santos",
    contact_name: "James Wilson", contact_phone: "+1 (555) 013-9022", direction: "outbound", started_at: "2026-07-24T09:15:00.000Z",
    duration_seconds: 725, overall_score: 89, outcome: "won", sentiment: "positive",
    summary: "Maya connected the product to a costly reporting gap and booked a technical walkthrough.",
    strengths: ["Quantified the pain", "Tailored explanation", "Strong close"], improvements: ["Confirm implementation timeframe earlier"],
    rubric_scores: { opening: 90, discovery: 92, communication: 88, objection_handling: 84, closing: 93 },
    transcript: "Agent: James, thanks for making the time. I reviewed the notes you sent. It sounds like reporting is taking several hours each week—is that right?",
    created_at: "2026-07-24T09:31:00.000Z",
  },
  {
    ...base, id: "demo-005", external_call_id: "ghl_demo_005", agent_id: "agent-liam", agent_name: "Liam Chen",
    contact_name: "Ava Garcia", contact_phone: "+1 (555) 012-4419", direction: "inbound", started_at: "2026-07-23T07:51:00.000Z",
    duration_seconds: 364, overall_score: 69, outcome: "lost", sentiment: "negative",
    summary: "The prospect's urgent support concern was answered, but the call ended without confirming resolution or a next step.",
    strengths: ["Stayed calm", "Provided the correct policy"],
    improvements: ["Acknowledge frustration sooner", "Confirm the issue is resolved", "Offer a clear next action"],
    rubric_scores: { opening: 72, discovery: 61, communication: 73, objection_handling: 68, closing: 59 },
    transcript: "Agent: Thanks for calling Northstar, this is Liam.\n\nContact: I have been waiting two days for an answer and I need this fixed today.\n\nAgent: Let me pull up the account and see what happened.",
    created_at: "2026-07-23T08:00:00.000Z",
  },
  {
    ...base, id: "demo-006", external_call_id: "ghl_demo_006", agent_id: "agent-sofia", agent_name: "Sofia Reyes",
    contact_name: "Ethan Brown", contact_phone: "+1 (555) 019-8820", direction: "outbound", started_at: "2026-07-22T03:32:00.000Z",
    duration_seconds: 518, overall_score: 83, outcome: "follow_up", sentiment: "positive",
    summary: "Sofia ran a focused discovery call and arranged a useful follow-up after confirming the key integration requirement.",
    strengths: ["Good pacing", "Relevant technical question", "Clear recap"], improvements: ["Surface the budget range"],
    rubric_scores: { opening: 86, discovery: 84, communication: 88, objection_handling: 79, closing: 81 },
    transcript: "Agent: Ethan, before we dive in, what would make this call useful for you?\n\nContact: I mainly need to know whether this works with our current CRM.",
    created_at: "2026-07-22T03:44:00.000Z",
  },
];
